### PR TITLE
Update build fix

### PR DESCRIPTION
**Pull request by milestorme**
removing ScriptPCH , repair build using new headers

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@milestorme Thanks for contributing

**Comment by BarbzYHOOL** [comment]
@Winfidonarleyan i know it's a simple PR but I had asked testers to test it first, so please, wait a bit in that case (too late now) (link here https://github.com/azerothcore/mod-learn-spells/issues/5 )

**Comment by Winfidonarleyan** [comment]
I don't think should test the obvious.

**Comment by BarbzYHOOL** [comment]
it's not about testing, it's about involving people in the project

**Pull request merged**
