### PR TITLE
Added Missing Spells for Hunter/Warrior/Paladin

### PR DESCRIPTION
**Pull request by Vanheden**
Added missing spells for Hunter/Warrior/Paladin

### CODE REVIEW

**Comment by Helias** [comment]
build fail

**Comment by Vanheden** [comment]
> build fail

Hmm it didn't fail for me when I compiled 2022-06-22. Let me try with newest updates on the core.

**Comment by Helias** [comment]
I updated the CI, try to update your branch with master

**Comment by Helias** [comment]
the error is during the startup

**Pull request closed without merging**
